((cperl-mode . ((dumb-jump-force-searcher . rg)
                (cperl-indent-level . 4)
                (cperl-close-paren-offset . -4)
                (cperl-indent-subs-specially . nil)
                (indent-tabs-mode . nil)
                (eval . (auto-fill-mode -1)))))
