#!/usr/bin/perl

use strict;
use warnings;

open(CONF, "configure.ac") or die "Couldn't open configure.ac: $!\n";

while (<CONF>) {
  if (/^AC_INIT\(\[stow\], \[(.+?)\]/) {
    print "$1\n";
    exit 0;
  }
}

exit 1;
